Pro/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Notes/', include('ProApp.urls' , namespace = 'notes')),
    path('accounts/', include('accounts.urls' , namespace = 'accounts')),
    path('', include('home.urls' , namespace = 'home')),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'note_app'
urlpatterns = [
    url(r'^$', views.all_notes, name = 'all_notes'),
    #url(r'^(?P<id>\d+)$', views.detail, name = 'note_detail')
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name = 'note_detail'),
    url(r'^Create$', views.note_add, name = 'add_note'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit, name = 'note_edit'),

]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout, login

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.home, name = 'home'),
    url(r'^login/$', login,{'template_name':'login.html'}),
    url(r'^logout/$', logout),
    url(r'^signup/$', views.register, name = 'register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile, name = 'profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile, name = 'edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password, name = 'change_password'),

]

ProApp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from ckeditor.fields import RichTextField

class Note(models.Model):
    user = models.ForeignKey(User , on_delete = models.CASCADE)
    title = models.CharField(max_length = 50)
    slug = models.SlugField(null = True, blank = True)
    content = RichTextField()
    created = models.DateTimeField(blank = True, default = datetime.datetime.now)
    active = models.BooleanField(default=True)
    tags = models.CharField(blank=True, max_length=100)
    img = models.ImageField(upload_to="notes-img", blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note, self).save(*args, **kwargs)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    headline = models.CharField(blank=True, max_length=100)
    slug = models.SlugField(null = True, blank = True)
    bio = models.TextField(blank=True)
    imt = models.ImageField(upload_to="profile_img")
    join_date = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return '%s' %(self.user)

def createProfile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user = kwargs['instance'])

post_save.connect(createProfile, sender = User)

ProApp/forms.py
from django import forms
from .models import Note
from ckeditor.widgets import CKEditorWidget

class NoteForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class profileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['headline', 'bio', 'imt']

ProApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Note
from .forms import NoteForm
from django.contrib.auth.models import User
from django.contrib import messages
from accounts.models import Profile
# Create your views here.

def all_notes(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    all_notes = Note.objects.filter(user=user)
    context = {
        'all_notes' : all_notes,
        'profile':profile
    }
    return render(request, 'notes.html', context)

def detail(request, slug):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    note = Note.objects.get(slug = slug)
    context = {
        'note' : note,
        'profile':profile

    }
    return render(request, 'one-note.html', context)

def note_add(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if request.method == 'POST':
        form = NoteForm(request.POST)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Note Added successfully.')
            return redirect('/Notes')

    else:
        form = NoteForm()

    context = {
        'form' : form,
        'profile':profile
    }
    return render(request, 'add.html', context)


def edit(request, slug):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    note = get_object_or_404(Note, slug = slug)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance = note)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/Notes')

    else:
        form = NoteForm(instance = note)

    context = {
        'form' : form,
        'profile':profile
    }
    return render(request, 'edit.html', context)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import logout, login, authenticate
from .models import Profile
from django.shortcuts import get_object_or_404
from .forms import UserForm, profileForm

def home(request):
    pass

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('/Notes')
    else:
        form = UserCreationForm()
    context = {
        'form' : form
    }
    return render(request,'signup.html', context)

def profile(request, slug):
    profile = get_object_or_404(Profile,slug = slug)
    context = {
        'profile': profile
    }
    return render(request, 'profile.html', context)

def edit_profile(request, slug):
    profile = get_object_or_404(Profile, slug = slug)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance = request.user)
        profile_form = profileForm(request.POST, request.FILES, instance = profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            new_profile = profile_form.save()
            return redirect('/')
    else:
        user_form = UserForm(instance = request.user)
        profile_form = profileForm(instance = profile)

    context = {
        'user_form' : user_form,
        'profile_form' : profile_form
    }
    return render(request, 'edit_profile.html', context)

def change_password(request, slug):
    profile = get_object_or_404(Profile, slug = slug)
    if request.method =='POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            return redirect('/')
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form' : password_form
    }
    return render(request, 'change_password.html', context)

ProApp/templates/add.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block  body%}

<div class="row">
  <div class="add_form">
    <form method="post">
      {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary"> Add Note!</button>
    {% endbuttons %}    </form>
  </div>
</div>
{% endblock  %}

ProApp/templates/all_notes.html
<h1> Hiiiii </h1>

<h3> All ... </h3>
<a href="{% url 'notes:add_note' %}">Add New Note</a>
<br>
<hr>
{% for note in all_notes %}
    <a href="{% url 'notes:note_detail' note.slug %}"> {{note}} </a>
    <br>
{% endfor %}

ProApp/templates/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}

<div class="row">
  <div class="add_form">
    <form method="post">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary"> Save Changes</button>
    {% endbuttons %}  </form>
  </div>
</div>


{% endblock  %}

ProApp/templates/note_detail.html
<h1> {{note}} </h1>
<hr>
<a href="{% url 'notes:note_edit' note.slug %}"> Edit </a>
<hr>
<h4> {{note.content|safe}} <h4>
<h5> {{note.created}} <h5>
<h4> {{note.active}} <h4>

ProApp/templates/notes.html
{% extends "base.html" %}
{% load static %}
    <!-- Start blog Area -->

    {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

    {% block body %}
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1> Your Recent Notes </h1>
            <p>
              Create, Update and Share!
            </p>
          </div>
        </div>
        <div class="row">
          {% for note in all_notes  %}
          <div class="single-blog col-lg-4 col-md-4">
            {% if note.img %}
            <img class="f-img img-fluid mx-auto" src="{{note.img.url}}" alt="">
            {% endif %}

            <h4>
              <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
            </h4>
            <p>
              {{note.content|safe|truncatewords:'20'}}
            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
              <div>
                <a href="#"><span>{{note.user.username}}</span></a>
              </div>
              <div class="meta">
                {{note.created|date:"j M"}}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    {% endblock  %}
    <!-- end blog Area -->

    <!-- start footer Area -->

ProApp/templates/one-note.html
{% extends "base.html" %}
{% load static %}


{% block body  %}
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1> {{note}} </h1>
            <p>
              {{note.created|date:"j M"}} | {{note.user.username}} | {{note.tags}}
            </p>
          </div>
        </div>
        <div class="row">
          <div class="single-blog col-lg-10 col-md-10">
            {{note.content|safe}}
            <img class="f-img img-fluid mx-auto post_banner" src="{{note.img.url}}" alt="">
            <h4>
            </h4>
            <p>
          </div>
        </div>
      </div>
    </section>
{% endblock  %}

accounts/templates/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body  %}

<div class="container page_body">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form password_form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Save Changes</button>
    {% endbuttons %}  </form>
</div>
{% endblock  %}

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block body  %}
<div class="container page_body">
  <form method="post">
    {% csrf_token %}
 {% bootstrap_form profile_form %}
  {% bootstrap_form user_form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Save Changes</button>
    {% endbuttons %}
  </form>
</div>
{% endblock  %}

accounts/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}

<div class="row">
  <div class="add_form">
    <form  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
</form>
  </div>
</div>
{% endblock  %}

accounts/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<div class="container">
  <center>
      <img src="{% if  profile.img %} {{profile.img.url}} {% endif %}" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
      <h3 class="media-heading">{{profile.user}} <small></small></h3>
      <span><strong>Skills: </strong></span>
          <span class="label label-warning">HTML5/CSS</span>
          <span class="label label-info">Adobe CS 5.5</span>
          <span class="label label-info">Microsoft Office</span>
          <span class="label label-success">Windows XP, Vista, 7</span>
      </center>
      <hr>
      <center>
      <p class="text-left"><strong>Bio: </strong><br>
        {{profile.bio}}
      <br>
      </center>
      <div class="row">
        <a href="{% url 'accounts:change_password' profile.slug %}"> Change Password </a>
        <<hr> </hr>
        <a href="{% url 'accounts:edit_profile' profile.slug %}"> Edit </a>
      </div>
</div>
{% endblock  %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}

<div class="row">
  <div class="add_form">
    <form  method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon-->
  <link rel="shortcut icon" href="img/fav.png">
  <!-- Author Meta -->
  <meta name="author" content="Colorlib">
  <!-- Meta Description -->
  <meta name="description" content="">
  <!-- Meta Keyword -->
  <meta name="keywords" content="">
  <!-- meta character set -->
  <meta charset="UTF-8">
  <!-- Site Title -->
  <title>Quick Notes</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'site-static/css/linearicons.css'%}">
    <link rel="stylesheet" href="{% static 'site-static/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'site-static/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'site-static/css/nice-select.css'%}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="{% static 'site-static/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'site-static/css/main.css'%}">
    <link rel="stylesheet" href="{% static 'site-static/css/mystyle.css'%}">

  </head>
  <body>

    <!-- Start Header Area -->


    <!-- End Header Area -->

    <!-- start banner Area -->

    <!-- End banner Area -->

    <!-- Start blog Area -->
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <div class="alert alert-success">
    <strong>Success!</strong> {{message}}
    {% endfor %}
      </div>
    </div>

  {% endif %}
    {% block body %}
    {% endblock  %}

    <!-- end blog Area -->

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-4  col-md-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">Contact Us</h6>
              <p>
                56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
              </p>
              <h3>012-6532-568-9746</h3>
              <h3>012-6532-568-97468</h3>
            </div>
          </div>
          <div class="col-lg-6  col-md-12">
            <div class="single-footer-widget newsletter">
              <h6>Newsletter</h6>
              <p>You can trust us. we only send promo offers, not a single spam.</p>
              <div id="mc_embed_signup">
                <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                  <div class="form-group row" style="width: 100%">
                    <div class="col-lg-8 col-md-12">
                      <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                      <div style="position: absolute; left: -5000px;">
                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                      </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                      <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                    </div>
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between">
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->


    <script src="{% static 'site-static/js/vendor/jquery-2.2.4.min.js'  %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'site-static/js/vendor/bootstrap.min.js'  %}"></script>
    <script src="{% static 'site-staticjs/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'site-static/js/jquery.nice-select.min.js'  %}"></script>
    <script src="{% static 'site-static/js/jquery.sticky.js'  %}"></script>
    <script src="{% static 'site-static/js/parallax.min.js'  %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'site-static/js/jquery.magnific-popup.min.js'  %}"></script>
    <script src="{% static 'site-static/js/waypoints.min.js'  %}"></script>
    <script src="{% static 'site-static/js/jquery.counterup.min.js'  %}"></script>
    <script src="{% static 'site-static/js/main.js'  %}"></script>

  </body>
</html>